version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redis_data:
  workers_data:
  flower_data:
  telegram_bot_data:

services:
  postgres:
    container_name: tracker_postgres
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: tracker_backend
    image: ${DOCKER_HUB_LOGIN}/simple_task_tracker_backend
    command: |
      bash -c '
      sleep 15 &&
      (python manage.py bot start & ) &&
      gunicorn --bind 0:9000 task_tracker.wsgi'
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - telegram_bot_data:/app/bot/bot_data
    depends_on:
      - postgres
      - redis

  nginx:
    container_name: tracker_nginx
    image: ${DOCKER_HUB_LOGIN}/simple_task_tracker_gateway
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - backend

  redis:
    container_name: tracker_redis
    image: redis:7.2-alpine
    env_file:
      - .env
    volumes:
      - redis_data:/data

  flower:
    container_name: tracker_flower
    image: mher/flower:2.0.0
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_BASIC_AUTH=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - ${FLOWER_PORT}:6666
    volumes:
      - flower_data:/data
    restart: always

  celery_worker_slow_queue:
    container_name: tracker_celery_worker_slow_queue
    image: ${DOCKER_HUB_LOGIN}/simple_task_tracker_backend
    env_file:
      - .env
    hostname: celery_worker_slow_queue
    entrypoint: celery
    command: -A task_tracker.celery worker -Q slow_queue -l info -n slow_queue --concurrency=1
    volumes:
      - workers_data:/app/workers_data
    links:
      - redis
    depends_on:
      - redis
      - postgres

  celery_worker_fast_queue:
    container_name: tracker_celery_worker_fast_queue
    image: ${DOCKER_HUB_LOGIN}/simple_task_tracker_backend
    env_file:
      - .env
    hostname: celery_worker_fast_queue
    entrypoint: celery
    command: -A task_tracker.celery worker -Q fast_queue -l info -n fast_queue --concurrency=10
    volumes:
      - workers_data:/app/workers_data
    links:
      - redis
    depends_on:
      - redis
      - postgres

  celery_beat_worker:
    container_name: tracker_celery_beat_worker
    image: ${DOCKER_HUB_LOGIN}/simple_task_tracker_backend
    env_file:
      - .env
    hostname: celery_beat_worker
    entrypoint: celery
    command: -A task_tracker.celery beat -l info
    volumes:
      - workers_data:/app/workers_data
    links:
      - redis
      - postgres
    depends_on:
      - celery_worker_fast_queue
      - celery_worker_slow_queue
      - redis