# Generated by Django 4.2.5 on 2023-09-15 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название задачи', max_length=120, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание задачи', verbose_name='Описание')),
                ('priority', models.CharField(choices=[('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='Низкий', help_text='Установите приоритет', max_length=120, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В процессе выполнения', 'В процессе выполнения'), ('Выполнено', 'Выполнено')], default='Ожидает выполнения', help_text='Выберите статус', max_length=120, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
