# Generated by Django 4.2.5 on 2024-02-12 06:55

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='В слаге содержится недопустимый символ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название задачи', max_length=120, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание задачи', verbose_name='Описание')),
                ('priority', models.CharField(choices=[('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='Низкий', help_text='Установите приоритет', max_length=120, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В процессе выполнения', 'В процессе выполнения'), ('Выполнено', 'Выполнено')], default='Ожидает выполнения', help_text='Выберите статус', max_length=120, verbose_name='Статус')),
                ('previous_status', models.CharField(blank=True, choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В процессе выполнения', 'В процессе выполнения'), ('Выполнено', 'Выполнено')], help_text='Выберите предыдущий статус', max_length=120, null=True, verbose_name='Предыдущий статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now, message='Дедлайн не может быть в прошлом!')], verbose_name='Дедлайн')),
                ('deadline_reminder', models.DateTimeField(blank=True, help_text='Если не заполнять, то напоминание придет за сутки до дедлайна. На отрезках менее суток лучше заполнять вручную', null=True, verbose_name='Когда напомнить о дедлайне')),
                ('is_notified', models.BooleanField(default=False, help_text='Уведомлен ли пользователь о приближении дедлайна', verbose_name='Уведомлен?')),
                ('is_done', models.BooleanField(default=False, help_text='Отмечено ли задание как выполненное', verbose_name='Выполнено')),
                ('done_by_time', models.DateTimeField(blank=True, help_text='Время, когда задача была отмечена выполненной', null=True, verbose_name='Время выполнения')),
                ('assigned_to', models.ForeignKey(default=django.contrib.auth.models.User, help_text='Выберите пользователя, который будет ответственен за задачу.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('author', models.ForeignKey(help_text='Выберите автора', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('done_by', models.ForeignKey(blank=True, help_text='Выберите пользователя, отметившего задачу выполненной', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='done_by', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил(а)')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tags', verbose_name='Тег')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Добавьте изображение', null=True, upload_to='images', verbose_name='Изображение')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracker.task')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите подходящий тег', related_name='tasks', through='tracker.TaskTag', to='tracker.tags', verbose_name='Тег'),
        ),
    ]
