# Generated by Django 4.2.5 on 2023-10-04 10:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='В слаге содержится недопустимый символ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(default=None, help_text='Выберите пользователя, который будет ответственен за задачу.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='task',
            name='done_by',
            field=models.ForeignKey(blank=True, help_text='Выберите пользователя, отметившего задачу выполненной', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='done_by', to=settings.AUTH_USER_MODEL, verbose_name='Пометил(а) как выполненное'),
        ),
        migrations.AddField(
            model_name='task',
            name='done_by_time',
            field=models.DateTimeField(blank=True, help_text='Время, когда задача была отмечена выполненной', null=True, verbose_name='Время выполнения'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tags', verbose_name='Тег')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите подходящий тег', related_name='tasks', through='tracker.TaskTag', to='tracker.tags', verbose_name='Тег'),
        ),
    ]
