# Generated by Django 4.2.5 on 2024-03-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tasktag',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='TaskTag',
        ),
    ]
