# Generated by Django 4.2.5 on 2024-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_tasktag_tag_remove_tasktag_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=None, help_text='Опубликовано ли задание для всеобщего доступа', verbose_name='Опубликовано?'),
        ),
    ]
