# Generated by Django 4.2.5 on 2024-03-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_task_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_published',
            new_name='is_draft',
        ),
    ]
