# Generated by Django 4.2.5 on 2023-09-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_tasktag_options_alter_tags_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(default='Без тега', help_text='Выберите подходящий тег', related_name='tasks', through='tracker.TaskTag', to='tracker.tags', verbose_name='Тег'),
        ),
    ]
