# Generated by Django 4.2.5 on 2023-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_task_done_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='previous_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
