# Generated by Django 4.2.5 on 2024-03-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_is_published_task_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_draft',
            field=models.BooleanField(default=None, help_text='Является ли задание черновиком', verbose_name='Черновик?'),
        ),
    ]
