# Generated by Django 4.2.5 on 2023-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_task_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='previous_status',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Предыдущий статус'),
        ),
    ]
