# Generated by Django 4.2.5 on 2023-09-20 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='В слаге содержится недопустимый символ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
    ]
