# Generated by Django 4.2.5 on 2023-10-16 13:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_task_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now, message='Дедлайн не может быть в прошлом!')], verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Отмечено ли задание как выполненное', verbose_name='Выполнено'),
        ),
    ]
