# Generated by Django 4.2.5 on 2023-09-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_tags_name_alter_tags_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите подходящий тег', related_name='tasks', through='tracker.TaskTag', to='tracker.tags', verbose_name='Тег'),
        ),
    ]
