# Generated by Django 4.2.5 on 2023-11-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_notified',
            field=models.BooleanField(default=False, help_text='Уведомлен ли пользователь о приближении дедлайна', verbose_name='Уведомлен?'),
        ),
    ]
