# Generated by Django 4.2.5 on 2023-11-22 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_task_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_reminder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 11, 13, 3, 56898, tzinfo=datetime.timezone.utc), null=True, verbose_name='Когда напомнить о дедлайне'),
        ),
    ]
