# Generated by Django 4.2.5 on 2023-11-22 11:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_task_deadline_alter_task_deadline_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now, message='Дедлайн не может быть в прошлом!')], verbose_name='Дедлайн'),
        ),
    ]
