# Generated by Django 4.2.5 on 2023-11-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_task_deadline_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда напомнить о дедлайне'),
        ),
    ]
