# Generated by Django 4.2.5 on 2023-12-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_comment_level_comment_lft_comment_rght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='parent',
        ),
    ]
