# Generated by Django 4.2.5 on 2024-01-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_rename_parent_comment_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В процессе выполнения', 'В процессе выполнения'), ('Выполнено', 'Выполнено')], max_length=120, null=True, verbose_name='Предыдущий статус'),
        ),
    ]
