# Generated by Django 4.2.5 on 2024-01-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_task_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте изображение', null=True, upload_to='tasks/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_reminder',
            field=models.DateTimeField(blank=True, help_text='Если не заполнять, то напоминание придет за сутки до дедлайна. На отрезках менее суток лучше заполнять вручную', null=True, verbose_name='Когда напомнить о дедлайне'),
        ),
        migrations.AlterField(
            model_name='task',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В процессе выполнения', 'В процессе выполнения'), ('Выполнено', 'Выполнено')], help_text='Выберите предыдущий статус', max_length=120, null=True, verbose_name='Предыдущий статус'),
        ),
    ]
