# Generated by Django 4.2.5 on 2024-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(blank=True, default=0, help_text='Сделать профиль приватным?', null=True, verbose_name='Скрыть профиль от неавторизованных пользователей'),
        ),
    ]
