# Generated by Django 4.2.5 on 2024-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='--------', help_text='Расскажите немного о себе', null=True, verbose_name='Кратко о себе'),
        ),
    ]
