# Generated by Django 4.2.5 on 2024-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, default='Не задано', help_text='Укажите имя пользователя в Telegram', max_length=250, null=True, verbose_name='Имя пользователя в Telegram'),
        ),
    ]
