# Generated by Django 4.2.5 on 2024-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, help_text='Укажите chat_id беседы с ботом', null=True, verbose_name='Введите chat_id беседы'),
        ),
    ]
