# Generated by Django 4.2.5 on 2024-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, default='Не задано', help_text='Укажите chat_id беседы с ботом', null=True, verbose_name='Chat_id беседы'),
        ),
    ]
