# Generated by Django 4.2.5 on 2024-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_in_telegram',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], default=True, help_text='Будут приходить уведомления о событиях в трекере', null=True, verbose_name='Уведомлять в Telegram?'),
        ),
    ]
