# Generated by Django 4.2.5 on 2024-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_notify_in_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notify_in_telegram',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], default=True, help_text='Будут ли приходить уведомления о событиях в трекере', null=True, verbose_name='Уведомлять в Telegram?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, help_text='Укажите chat_id беседы с ботом', null=True, verbose_name='Chat_id беседы'),
        ),
    ]
