# Generated by Django 4.2.5 on 2024-03-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Укажите chat_id беседы с ботом', null=True, verbose_name='Chat_id беседы'),
        ),
    ]
